title: CoMPAS Documentation
description: This is the documentation for CoMPAS, a comprehensive software package.
theme: just-the-docs

url: https://philippilievskibearingpointcom.github.io/compas-documentation/

aux_links:
  Template Repository: https://github.com/philippilievskibearingpointcom/compas-documentation/
